before_script:
  # Add deploy private key to the docker image (detail https://docs.gitlab.com/ce/ci/ssh_keys/README.html)
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

image: node:6.9

lint:
  stage: test
  script:
    - npm install
    - npm run lint
